"""Add product route prices and order discount

Revision ID: 30a71e655eca
Revises: 0a10ddc75bd6
Create Date: 2025-09-30 16:57:28.159310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30a71e655eca'
down_revision = '0a10ddc75bd6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('discount_percentage', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'discount_percentage')
    # ### end Alembic commands ### 