"""add_token_field_to_users

Revision ID: 3796d94d8acb
Revises: 96d2df3f513c
Create Date: 2025-10-03 17:58:26.949504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3796d94d8acb'
down_revision = '96d2df3f513c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    import uuid
    
    # Add the token column as nullable first
    op.add_column('users', sa.Column('token', sa.String(), nullable=True))
    
    # Update existing users with unique UUID tokens
    connection = op.get_bind()
    result = connection.execute(sa.text("SELECT id FROM users WHERE token IS NULL"))
    for row in result:
        connection.execute(
            sa.text("UPDATE users SET token = :token WHERE id = :user_id"),
            {"token": str(uuid.uuid4()), "user_id": row[0]}
        )
    
    # Now make the column NOT NULL
    op.alter_column('users', 'token', nullable=False)
    op.create_index(op.f('ix_users_token'), 'users', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_token'), table_name='users')
    op.drop_column('users', 'token')
    # ### end Alembic commands ### 