"""change_quantity_to_decimal_support

Revision ID: 3928f3e26d4f
Revises: f4d1333f244b
Create Date: 2025-10-29 13:10:36.448730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3928f3e26d4f'
down_revision = 'f4d1333f244b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'discount_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'discount_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    # ### end Alembic commands ### 