"""Add product route prices table

Revision ID: 96d2df3f513c
Revises: 30a71e655eca
Create Date: 2025-09-30 16:58:28.656117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96d2df3f513c'
down_revision = '30a71e655eca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_route_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'route_id', name='_product_route_uc')
    )
    op.create_index(op.f('ix_product_route_prices_id'), 'product_route_prices', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_route_prices_id'), table_name='product_route_prices')
    op.drop_table('product_route_prices')
    # ### end Alembic commands ### 